#### 模拟抛出异常

```java
// 调用有返回值方法异常
@Test
public void test_throw_error_return_value() {
    Mockito.when(userMapper.selectById(Mockito.any()))
            .thenThrow(
                    new RuntimeException("User not found ...")
            );
    assertThrows(RuntimeException.class, () -> userService.getUserById(1));
}

// 调用无返回值方法异常
@Test
public void test_throw_error_no_return_value() {
    Mockito.doThrow(new RuntimeException("error ..."))
            .when(userMapper).executeNoReturnValue(Mockito.any());
    assertThrows(RuntimeException.class, () -> userService._01_test_no_return_value());
}

// 次数验证
@Test
public void test_throw_error_action_num() {
    // 第一次调用时 doNothing，第二次调用时抛出异常
    Mockito.doNothing()
            .doThrow(new RuntimeException("error ..."))
            .when(userMapper).executeNoReturnValue(Mockito.any());

    userService._01_test_no_return_value();
    assertThrows(RuntimeException.class, () -> userService._01_test_no_return_value());

    // 验证方法调用次数
    Mockito.verify(userMapper, Mockito.times(2)).executeNoReturnValue(Mockito.any());
}
```
